"""initial

Revision ID: 5102d6edd851
Revises: 
Create Date: 2026-09-06 23:57:44.541568
"""
from __future__ import annotations
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('ua', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('credit_balances',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('low_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_dedupe_key'), 'jobs', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_run_at'), 'jobs', ['run_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('model_catalog',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('cli_alias', sa.String(length=64), nullable=True),
    sa.Column('context_window', sa.Integer(), server_default='200000', nullable=False),
    sa.Column('max_output', sa.Integer(), server_default='8192', nullable=False),
    sa.Column('supports_thinking', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('supports_vision', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('credit_per_1k_input', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('credit_per_1k_output', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('credit_per_1k_cache_read', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model_id')
    )
    op.create_table('owner_profiles',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('visibility', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('plans',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('monthly_credits', sa.Integer(), server_default='300', nullable=False),
    sa.Column('max_agents', sa.Integer(), server_default='1', nullable=False),
    sa.Column('max_share_links', sa.Integer(), server_default='2', nullable=False),
    sa.Column('max_knowledge_mb', sa.Integer(), server_default='50', nullable=False),
    sa.Column('max_network_nodes', sa.Integer(), server_default='300', nullable=False),
    sa.Column('turn_cost_cap_credits', sa.Integer(), server_default='30', nullable=False),
    sa.Column('daily_credit_cap', sa.Integer(), server_default='100', nullable=False),
    sa.Column('visitor_turns_per_day', sa.Integer(), server_default='200', nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('turn_events',
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('turn_id', 'seq')
    )
    op.create_table('usage_daily',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('credits', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('visitor_turns', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('owner_id', 'day')
    )
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=8), server_default='ko', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Seoul', nullable=False),
    sa.Column('role', sa.String(length=16), server_default='user', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('plan_cycle_anchor', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('failed_logins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_plan_id'), 'users', ['plan_id'], unique=False)
    op.create_table('agents',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role_line', sa.String(length=160), server_default='', nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('persona', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('custom_instructions', sa.Text(), server_default='', nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('disclosure_policy', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('greeting', sa.Text(), server_default='', nullable=False),
    sa.Column('suggested_questions', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('language', sa.String(length=8), server_default='auto', nullable=False),
    sa.Column('theme', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('voice', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('visitor_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('thinking_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_table('auth_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('raw_profile', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('refresh_hash', sa.String(length=128), nullable=False),
    sa.Column('ua', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_hash')
    )
    op.create_index(op.f('ix_auth_sessions_family_id'), 'auth_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('connections',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_label', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('capabilities', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_cursor', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'provider', 'account_label')
    )
    op.create_index(op.f('ix_connections_owner_id'), 'connections', ['owner_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_ledger_owner_created', 'credit_ledger', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_credit_ledger_owner_id'), 'credit_ledger', ['owner_id'], unique=False)
    op.create_index('uq_credit_ledger_turn_ref', 'credit_ledger', ['ref_type', 'ref_id'], unique=True, postgresql_where="kind = 'turn'")
    op.create_table('email_verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    op.create_table('facts',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('predicate', sa.String(length=200), nullable=False),
    sa.Column('object', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), server_default='context', nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0.8', nullable=False),
    sa.Column('visibility', sa.String(length=24), server_default='private', nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('source_turn_id', sa.UUID(), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_agent_id'), 'facts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_facts_owner_id'), 'facts', ['owner_id'], unique=False)
    op.create_index('ix_facts_owner_status', 'facts', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_facts_visitor_id'), 'facts', ['visitor_id'], unique=False)
    op.create_table('invites',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('max_uses', sa.Integer(), server_default='1', nullable=False),
    sa.Column('used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_invites_created_by'), 'invites', ['created_by'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='processing', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default='private', nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('text_preview', sa.Text(), server_default='', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_agent_id'), 'knowledge_documents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_owner_id'), 'knowledge_documents', ['owner_id'], unique=False)
    op.create_table('knowledge_faqs',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=16), server_default='public', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('source', sa.String(length=24), server_default='manual', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_faqs_agent_id'), 'knowledge_faqs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_faqs_owner_id'), 'knowledge_faqs', ['owner_id'], unique=False)
    op.create_table('network_nodes',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('visibility', sa.String(length=16), server_default='private', nullable=False),
    sa.Column('importance', sa.Integer(), server_default='3', nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=24), server_default='manual', nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_network_nodes_name_trgm', 'network_nodes', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_network_nodes_owner_id'), 'network_nodes', ['owner_id'], unique=False)
    op.create_index('uq_network_nodes_ext', 'network_nodes', ['owner_id', 'source', 'external_ref'], unique=True, postgresql_where='external_ref IS NOT NULL')
    op.create_table('network_proposals',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('source_turn_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_proposals_owner_id'), 'network_proposals', ['owner_id'], unique=False)
    op.create_index(op.f('ix_network_proposals_status'), 'network_proposals', ['status'], unique=False)
    op.create_table('notification_channels',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=80), server_default='', nullable=False),
    sa.Column('config_enc', sa.Text(), nullable=False),
    sa.Column('config_public', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_channels_owner_id'), 'notification_channels', ['owner_id'], unique=False)
    op.create_table('notification_rules',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('channel_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('min_urgency', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_rules_owner_id'), 'notification_rules', ['owner_id'], unique=False)
    op.create_table('notifications',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_owner_id'), 'notifications', ['owner_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('password_resets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.create_table('purchases',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('credits', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_purchases_owner_id'), 'purchases', ['owner_id'], unique=False)
    op.create_table('tool_spans',
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_preview', sa.Text(), server_default='', nullable=False),
    sa.Column('is_error', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_spans_owner_id'), 'tool_spans', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tool_spans_turn_id'), 'tool_spans', ['turn_id'], unique=False)
    op.create_table('uploads',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_owner_id'), 'uploads', ['owner_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=32), server_default='', nullable=False),
    sa.Column('model_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('units', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('credits', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_agent_id'), 'usage_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_usage_events_created_at'), 'usage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_owner_id'), 'usage_events', ['owner_id'], unique=False)
    op.create_index(op.f('ix_usage_events_turn_id'), 'usage_events', ['turn_id'], unique=False)
    op.create_table('integration_emails',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('ext_id', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=True),
    sa.Column('from_addr', sa.String(length=320), server_default='', nullable=False),
    sa.Column('to_addrs', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('subject', sa.Text(), server_default='', nullable=False),
    sa.Column('snippet', sa.Text(), server_default='', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('importance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unread', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'ext_id')
    )
    op.create_index(op.f('ix_integration_emails_connection_id'), 'integration_emails', ['connection_id'], unique=False)
    op.create_index(op.f('ix_integration_emails_owner_id'), 'integration_emails', ['owner_id'], unique=False)
    op.create_index(op.f('ix_integration_emails_received_at'), 'integration_emails', ['received_at'], unique=False)
    op.create_table('integration_events',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('ext_id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('location', sa.Text(), server_default='', nullable=False),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='confirmed', nullable=False),
    sa.Column('description_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'ext_id')
    )
    op.create_index(op.f('ix_integration_events_connection_id'), 'integration_events', ['connection_id'], unique=False)
    op.create_index(op.f('ix_integration_events_owner_id'), 'integration_events', ['owner_id'], unique=False)
    op.create_index(op.f('ix_integration_events_start_at'), 'integration_events', ['start_at'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('heading', sa.Text(), server_default='', nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', text)", persisted=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index('ix_knowledge_chunks_embedding', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_knowledge_chunks_owner_id'), 'knowledge_chunks', ['owner_id'], unique=False)
    op.create_index('ix_knowledge_chunks_tsv', 'knowledge_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('network_edges',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('src_id', sa.UUID(), nullable=False),
    sa.Column('dst_id', sa.UUID(), nullable=False),
    sa.Column('rel', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=12), server_default='directed', nullable=False),
    sa.Column('strength', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('since', sa.Date(), nullable=True),
    sa.Column('until', sa.Date(), nullable=True),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('visibility', sa.String(length=16), server_default='private', nullable=False),
    sa.Column('source', sa.String(length=24), server_default='manual', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['network_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_id'], ['network_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'src_id', 'dst_id', 'rel')
    )
    op.create_index(op.f('ix_network_edges_dst_id'), 'network_edges', ['dst_id'], unique=False)
    op.create_index(op.f('ix_network_edges_owner_id'), 'network_edges', ['owner_id'], unique=False)
    op.create_index(op.f('ix_network_edges_src_id'), 'network_edges', ['src_id'], unique=False)
    op.create_table('network_interactions',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('ref', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['network_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_interactions_at'), 'network_interactions', ['at'], unique=False)
    op.create_index(op.f('ix_network_interactions_node_id'), 'network_interactions', ['node_id'], unique=False)
    op.create_index(op.f('ix_network_interactions_owner_id'), 'network_interactions', ['owner_id'], unique=False)
    op.create_table('share_links',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('code', postgresql.CITEXT(), nullable=False),
    sa.Column('label', sa.String(length=80), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_conversations', sa.Integer(), nullable=True),
    sa.Column('conversation_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('turn_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_share_links_agent_id'), 'share_links', ['agent_id'], unique=False)
    op.create_index(op.f('ix_share_links_owner_id'), 'share_links', ['owner_id'], unique=False)
    op.create_table('visitors',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('share_link_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('matched_node_id', sa.UUID(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('turn_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_link_id'], ['share_links.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_visitors_agent_id'), 'visitors', ['agent_id'], unique=False)
    op.create_index(op.f('ix_visitors_owner_id'), 'visitors', ['owner_id'], unique=False)
    op.create_index(op.f('ix_visitors_share_link_id'), 'visitors', ['share_link_id'], unique=False)
    op.create_table('conversations',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('share_link_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=160), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unread_owner', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('simulated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_link_id'], ['share_links.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_owner_id'), 'conversations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_conversations_share_link_id'), 'conversations', ['share_link_id'], unique=False)
    op.create_index(op.f('ix_conversations_visitor_id'), 'conversations', ['visitor_id'], unique=False)
    op.create_table('inbox_items',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('owner_reply', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_items_agent_id'), 'inbox_items', ['agent_id'], unique=False)
    op.create_index(op.f('ix_inbox_items_conversation_id'), 'inbox_items', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_inbox_items_kind'), 'inbox_items', ['kind'], unique=False)
    op.create_index(op.f('ix_inbox_items_owner_id'), 'inbox_items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_inbox_items_status'), 'inbox_items', ['status'], unique=False)
    op.create_index(op.f('ix_inbox_items_visitor_id'), 'inbox_items', ['visitor_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('content_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('cards', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_owner_id'), 'messages', ['owner_id'], unique=False)
    op.create_index(op.f('ix_messages_turn_id'), 'messages', ['turn_id'], unique=False)
    op.create_table('turns',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('client_turn_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('provider', sa.String(length=32), server_default='', nullable=False),
    sa.Column('model_id', sa.String(length=128), server_default='', nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('credits', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ttft_ms', sa.Integer(), nullable=True),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tool_call_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('injection_suspect', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('redactions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_text', sa.Text(), server_default='', nullable=False),
    sa.Column('answer_text', sa.Text(), server_default='', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_agent_id'), 'turns', ['agent_id'], unique=False)
    op.create_index(op.f('ix_turns_client_turn_id'), 'turns', ['client_turn_id'], unique=False)
    op.create_index(op.f('ix_turns_conversation_id'), 'turns', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_turns_owner_id'), 'turns', ['owner_id'], unique=False)
    op.create_index(op.f('ix_turns_started_at'), 'turns', ['started_at'], unique=False)
    op.create_index(op.f('ix_turns_status'), 'turns', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_status'), table_name='turns')
    op.drop_index(op.f('ix_turns_started_at'), table_name='turns')
    op.drop_index(op.f('ix_turns_owner_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_conversation_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_client_turn_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_agent_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_messages_turn_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_owner_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_inbox_items_visitor_id'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_status'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_owner_id'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_kind'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_conversation_id'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_agent_id'), table_name='inbox_items')
    op.drop_table('inbox_items')
    op.drop_index(op.f('ix_conversations_visitor_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_share_link_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_owner_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_visitors_share_link_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_owner_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_agent_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_share_links_owner_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_agent_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_network_interactions_owner_id'), table_name='network_interactions')
    op.drop_index(op.f('ix_network_interactions_node_id'), table_name='network_interactions')
    op.drop_index(op.f('ix_network_interactions_at'), table_name='network_interactions')
    op.drop_table('network_interactions')
    op.drop_index(op.f('ix_network_edges_src_id'), table_name='network_edges')
    op.drop_index(op.f('ix_network_edges_owner_id'), table_name='network_edges')
    op.drop_index(op.f('ix_network_edges_dst_id'), table_name='network_edges')
    op.drop_table('network_edges')
    op.drop_index('ix_knowledge_chunks_tsv', table_name='knowledge_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_knowledge_chunks_owner_id'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_embedding', table_name='knowledge_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_integration_events_start_at'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_owner_id'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_connection_id'), table_name='integration_events')
    op.drop_table('integration_events')
    op.drop_index(op.f('ix_integration_emails_received_at'), table_name='integration_emails')
    op.drop_index(op.f('ix_integration_emails_owner_id'), table_name='integration_emails')
    op.drop_index(op.f('ix_integration_emails_connection_id'), table_name='integration_emails')
    op.drop_table('integration_emails')
    op.drop_index(op.f('ix_usage_events_turn_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_owner_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_created_at'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_agent_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_uploads_owner_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_tool_spans_turn_id'), table_name='tool_spans')
    op.drop_index(op.f('ix_tool_spans_owner_id'), table_name='tool_spans')
    op.drop_table('tool_spans')
    op.drop_index(op.f('ix_purchases_owner_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_owner_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_rules_owner_id'), table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_notification_channels_owner_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_network_proposals_status'), table_name='network_proposals')
    op.drop_index(op.f('ix_network_proposals_owner_id'), table_name='network_proposals')
    op.drop_table('network_proposals')
    op.drop_index('uq_network_nodes_ext', table_name='network_nodes', postgresql_where='external_ref IS NOT NULL')
    op.drop_index(op.f('ix_network_nodes_owner_id'), table_name='network_nodes')
    op.drop_index('ix_network_nodes_name_trgm', table_name='network_nodes', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('network_nodes')
    op.drop_index(op.f('ix_knowledge_faqs_owner_id'), table_name='knowledge_faqs')
    op.drop_index(op.f('ix_knowledge_faqs_agent_id'), table_name='knowledge_faqs')
    op.drop_table('knowledge_faqs')
    op.drop_index(op.f('ix_knowledge_documents_owner_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_agent_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_invites_created_by'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_facts_visitor_id'), table_name='facts')
    op.drop_index('ix_facts_owner_status', table_name='facts')
    op.drop_index(op.f('ix_facts_owner_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_agent_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index('uq_credit_ledger_turn_ref', table_name='credit_ledger', postgresql_where="kind = 'turn'")
    op.drop_index(op.f('ix_credit_ledger_owner_id'), table_name='credit_ledger')
    op.drop_index('ix_credit_ledger_owner_created', table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_connections_owner_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_family_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_plan_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('worker_heartbeats')
    op.drop_table('usage_daily')
    op.drop_table('turn_events')
    op.drop_table('system_settings')
    op.drop_table('plans')
    op.drop_table('owner_profiles')
    op.drop_table('model_catalog')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_dedupe_key'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('credit_balances')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
