"""community: boards, posts, comments, reactions, views, reports, jobs

Autogenerate also reported three existing partial indexes as removed — it cannot see
their WHERE clauses — and dropping them would take out the turn invariants and job
dedupe. Those ops are deliberately not here.

Revision ID: 326c37e7ffa8
Revises: 0008_user_identity
Create Date: 2026-09-08 19:08:06.548893
"""
from __future__ import annotations
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = "0009_community"
down_revision = '0008_user_identity'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_boards',
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='discussion', nullable=False),
    sa.Column('icon', sa.String(length=24), server_default='', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('post_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('community_jobs',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), server_default='', nullable=False),
    sa.Column('employment_type', sa.String(length=24), server_default='fulltime', nullable=False),
    sa.Column('experience_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('apply_url', sa.Text(), server_default='', nullable=False),
    sa.Column('posted_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_jobs_posted_by'), 'community_jobs', ['posted_by'], unique=False)
    op.create_index(op.f('ix_community_jobs_status'), 'community_jobs', ['status'], unique=False)
    op.create_table('community_posts',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='published', nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hot_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('client_token', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['board_id'], ['community_boards.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'client_token', name='uq_community_posts_author_token')
    )
    op.create_index(op.f('ix_community_posts_author_id'), 'community_posts', ['author_id'], unique=False)
    op.create_index('ix_community_posts_board_created', 'community_posts', ['board_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_community_posts_board_id'), 'community_posts', ['board_id'], unique=False)
    op.create_index('ix_community_posts_hot', 'community_posts', ['hot_score', 'created_at'], unique=False)
    op.create_index(op.f('ix_community_posts_status'), 'community_posts', ['status'], unique=False)
    op.create_table('community_reactions',
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='like', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'user_id', 'kind', name='uq_community_reaction')
    )
    op.create_index(op.f('ix_community_reactions_target_id'), 'community_reactions', ['target_id'], unique=False)
    op.create_index(op.f('ix_community_reactions_user_id'), 'community_reactions', ['user_id'], unique=False)
    op.create_table('community_reports',
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_reports_reporter_id'), 'community_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_community_reports_status'), 'community_reports', ['status'], unique=False)
    op.create_index(op.f('ix_community_reports_target_id'), 'community_reports', ['target_id'], unique=False)
    op.create_table('community_comments',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='published', nullable=False),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('depth', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_comments_author_id'), 'community_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_comments_parent_id'), 'community_comments', ['parent_id'], unique=False)
    op.create_index('ix_community_comments_post_created', 'community_comments', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_community_comments_post_id'), 'community_comments', ['post_id'], unique=False)
    op.create_table('community_post_views',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('viewer_key', sa.String(length=64), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'viewer_key', 'day', name='uq_community_post_view')
    )
    op.create_index(op.f('ix_community_post_views_post_id'), 'community_post_views', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_post_views_post_id'), table_name='community_post_views')
    op.drop_table('community_post_views')
    op.drop_index(op.f('ix_community_comments_post_id'), table_name='community_comments')
    op.drop_index('ix_community_comments_post_created', table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_parent_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_author_id'), table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index(op.f('ix_community_reports_target_id'), table_name='community_reports')
    op.drop_index(op.f('ix_community_reports_status'), table_name='community_reports')
    op.drop_index(op.f('ix_community_reports_reporter_id'), table_name='community_reports')
    op.drop_table('community_reports')
    op.drop_index(op.f('ix_community_reactions_user_id'), table_name='community_reactions')
    op.drop_index(op.f('ix_community_reactions_target_id'), table_name='community_reactions')
    op.drop_table('community_reactions')
    op.drop_index(op.f('ix_community_posts_status'), table_name='community_posts')
    op.drop_index('ix_community_posts_hot', table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_board_id'), table_name='community_posts')
    op.drop_index('ix_community_posts_board_created', table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_author_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_community_jobs_status'), table_name='community_jobs')
    op.drop_index(op.f('ix_community_jobs_posted_by'), table_name='community_jobs')
    op.drop_table('community_jobs')
    op.drop_table('community_boards')
    # ### end Alembic commands ###
